[git_status]
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
staged = ''
up_to_date = 'âœ“'

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[direnv]
disabled = false
format = '$loaded$allowed'
loaded_msg = 'ğŸ“'
unloaded_msg = ''
allowed_msg = 'âœ”ï¸'
denied_msg = 'âŒ'

[sudo]
style = 'bold green'
symbol = 'ğŸ‘©â€ğŸ’» '
disabled = false

[package]
disabled = true

[python]
pyenv_version_name = false
format = '[${symbol}(${version}) ]($style)'
version_format = '$major.$minor'
